CREATE TABLE "TB_EVAL_SHEET" (
	"SHEET_CD"	VARCHAR2(20)		NOT NULL,
	"STEP_CD"	VARCHAR2(20)		NOT NULL,
	"STAFF_TYPE"	VARCHAR2(20)		NOT NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_SYS_ACS_HST" (
	"SYS_ACS_HST_CD"	VARCHAR2(20)		NOT NULL,
	"SYS_CD"	VARCHAR2(20)		NOT NULL,
	"USR_TYPE"	VARCHAR2(20)		NOT NULL,
	"USR_ID"	VARCHAR2(20)		NOT NULL,
	"ACS_DATE"	VARCHAR2(14)		NOT NULL,
	"LOGIN_DATE"	VARCHAR2(14)		NULL,
	"LOGOUT_DATE"	VARCHAR2(14)		NULL,
	"ACS_IP"	VARCHAR2(100)		NULL,
	"USER_AGENT"	VARCHAR2(100)		NULL,
	"ADMIN_YN"	VARCHAR2(1)		NOT NULL,
	"ACS_TYPE"	VARCHAR2(20)		NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"C RE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_APP_AWARD" (
	"AWARD_CD"	VARCHAR2(20)		NOT NULL,
	"APP_CD"	VARCHAR2(20)		NOT NULL,
	"AWARD_TYPE"	VARCHAR2(20)		NOT NULL,
	"AWARD_NM"	VARCHAR2(200)		NOT NULL,
	"ISSUE_DATE"	DATE		NOT NULL,
	"ISSUER"	VARCHAR2(100)		NOT NULL,
	"AWARD_DESC"	VARCHAR2(500)		NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_MSG_SND_HST" (
	"MSG_CD"	VARCHAR2(20)		NOT NULL,
	"MSG_TYPE_CD"	VARCHAR2(20)		NOT NULL,
	"SND_USR_CD"	VARCHAR2(20)		NOT NULL,
	"SND_LOGIN_ID"	VARCHAR2(50)		NOT NULL,
	"SDN_USR_NM"	VARCHAR2(100)		NOT NULL,
	"SND_DATE"	DATE		NOT NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_APP_CAREER" (
	"CAREER_CD"	VARCHAR2(20)		NOT NULL,
	"APP_CD"	VARCHAR2(20)		NOT NULL,
	"WORK_START_DATE"	DATE		NOT NULL,
	"WORK_END_DATE"	DATE		NULL,
	"EMPLOYED_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"WORK_PERIOD"	NUMBER(10)		NOT NULL,
	"COMPANY_NM"	VARCHAR2(100)		NOT NULL,
	"POSITION"	VARCHAR2(100)		NOT NULL,
	"TASK_DESC"	VARCHAR2(500)		NOT NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_EVAL_TOTAL_SCORE" (
	"TOTAL_CD"	VARCHAR2(20)		NOT NULL,
	"STEP_CD"	VARCHAR2(20)		NOT NULL,
	"APP_CD"	VARCHAR2(20)		NOT NULL,
	"TOTAL_AVG"	NUMBER(5,2)		NOT NULL,
	"EXCEPTED_AVG"	NUMBER(5,2)		NOT NULL,
	"PASS_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_APP_REC" (
	"REC_CD"	VARCHAR2(20)		NOT NULL,
	"APP_CD"	VARCHAR2(20)		NOT NULL,
	"NM"	VARCHAR2(100)		NOT NULL,
	"ORG"	VARCHAR2(100)		NOT NULL,
	"POSITION"	VARCHAR2(100)		NOT NULL,
	"RELATION"	VARCHAR2(100)		NOT NULL,
	"REMARKS"	VARCHAR2(500)		NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_EVAL_RESULT" (
	"RESULT_CD"	VARCHAR2(20)		NOT NULL,
	"JDG_CD"	VARCHAR2(20)		NOT NULL,
	"APP_CD"	VARCHAR2(20)		NOT NULL,
	"SHEET_CD"	VARCHAR2(20)		NOT NULL,
	"OPINION"	VARCHAR2(4000)		NULL,
	"MINUTES"	VARCHAR2(4000)		NULL,
	"CONFIRMED_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_APP_LANG" (
	"LANG_CD"	VARCHAR2(20)		NOT NULL,
	"APP_CD"	VARCHAR2(20)		NOT NULL,
	"EXAM_CD"	VARCHAR2(20)		NOT NULL,
	"EXAM_NM"	VARCHAR2(100)		NULL,
	"SCORE"	VARCHAR2(50)		NULL,
	"GRADE"	VARCHAR2(50)		NULL,
	"ISSUE_DATE"	DATE		NOT NULL,
	"ISSUER"	VARCHAR2(50)		NOT NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_SEL_EVAL_JDG" (
	"JDG_CD"	VARCHAR2(20)		NOT NULL,
	"STEP_CD"	VARCHAR2(20)		NOT NULL,
	"FIELD_CD"	VARCHAR2(20)		NOT NULL,
	"JDG_DIV"	VARCHAR2(20)		NOT NULL,
	"USR_ID"	VARCHAR2(20)		NOT NULL,
	"NM"	VARCHAR2(100)		NOT NULL,
	"CHAIR_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"OATH_AGREE_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"OATH_AGREE_DATE"	DATE		NULL,
	"CONFIRMED_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_NTC_INFO" (
	"NTC_INFO_CD"	VARCHAR2(20)		NOT NULL,
	"NTC_CD"	VARCHAR2(20)		NOT NULL,
	"NTC_INFO_TYPE"	VARCHAR2(20)		NOT NULL,
	"NTC_INFO_CNTS"	CLOB		NOT NULL,
	"UPLD_FILE_CD"	VARCHAR2(20)		NOT NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_NTC" (
	"NTC_CD"	VARCHAR2(20)		NOT NULL,
	"NTC_NUM"	VARCHAR2(20)		NOT NULL,
	"NTC_TYPE"	VARCHAR2(20)		NOT NULL,
	"NTC_YEAR"	VARCHAR2(4)		NOT NULL,
	"NTC_SMT"	VARCHAR2(20)		NULL,
	"NTC_NM"	VARCHAR2(200)		NOT NULL,
	"NTC_STATUS"	VARCHAR2(20)	DEFAULT '0'	NOT NULL,
	"REQUIRED_CNT"	NUMBER(3)		NOT NULL,
	"NTC_START_DATE"	DATE		NOT NULL,
	"REG_START_DATE"	DATE		NOT NULL,
	"REG_END_DATE"	DATE		NOT NULL,
	"HIRING_DATE"	DATE		NOT NULL,
	"RSCH_START_DATE"	DATE		NULL,
	"RSCH_END_DATE"	DATE		NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_APP_TR" (
	"TR_CD"	VARCHAR2(20)		NOT NULL,
	"APP_CD"	VARCHAR2(20)		NOT NULL,
	"TR_ORG_NM"	VARCHAR2(100)		NULL,
	"TR_START_DATE"	DATE		NOT NULL,
	"TR_END_DATE"	DATE		NOT NULL,
	"TR_DESC"	VARCHAR2(500)		NOT NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_SYS_MENU" (
	"MENU_CD"	VARCHAR2(20)		NOT NULL,
	"SYS_MENU_CD"	VARCHAR2(20)		NULL,
	"UPR_MENU_CD"	VARCHAR2(20)		NULL,
	"MENU_NM"	VARCHAR2(80)		NULL,
	"SYS_CD"	VARCHAR2(20)		NULL,
	"MENU_LVL"	NUMBER(5)		NOT NULL,
	"MENU_SORT"	NUMBER(5)		NOT NULL,
	"MENU_URL"	VARCHAR2(300)		NULL,
	"MENU_USE_YN"	VARCHAR2(1)		NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"C RE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_APP_SELF_INTRO" (
	"INTRO_CD"	VARCHAR2(20)		NOT NULL,
	"APP_CD"	VARCHAR2(20)		NOT NULL,
	"INTRO_CNTS"	CLOB		NOT NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_EVAL_SCORE" (
	"SCORE_CD"	VARCHAR2(20)		NOT NULL,
	"QST_CD"	VARCHAR2(20)		NOT NULL,
	"RESULT_CD"	VARCHAR2(20)		NOT NULL,
	"RESULT_SCORE"	NUMBER(3)		NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_APP_USR" (
	"APP_USR_CD"	VARCHAR2(20)		NOT NULL,
	"USR_ID"	VARCHAR2(20)		NULL,
	"NM"	VARCHAR2(100)		NOT NULL,
	"EMAIL"	VARCHAR2(100)		NOT NULL,
	"PW"	VARCHAR2(100)		NOT NULL,
	"BIRTH_DATE"	VARCHAR2(100)		NOT NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NOT NULL,
	"CRE_PGM"	VARCHAR2(100)		NOT NULL,
	"CRE_IP"	VARCHAR2(20)		NOT NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_CMM" (
	"LRG_CD"	VARCHAR2(20)		NOT NULL,
	"SMALL_CD"	VARCHAR2(20)		NOT NULL,
	"CD_NM"	VARCHAR2(100)		NOT NULL,
	"SYS_CD"	VARCHAR2(20)		NOT NULL,
	"SORT_ORDER"	NUMBER(5)		NOT NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_APP" (
	"APP_CD"	VARCHAR2(20)		NOT NULL,
	"NTC_CD"	VARCHAR2(20)		NOT NULL,
	"NTC_FIELD_ID"	VARCHAR2(20)		NOT NULL,
	"APP_USR_CD"	VARCHAR2(20)		NOT NULL,
	"NM"	VARCHAR2(100)		NOT NULL,
	"HANJA_NM"	VARCHAR2(100)		NOT NULL,
	"ENG_NM"	VARCHAR2(100)		NULL,
	"APP_STATUS"	VARCHAR2(20)	DEFAULT '1'	NOT NULL,
	"PASS_STEP"	VARCHAR2(20)	DEFAULT '0'	NOT NULL,
	"QUAL_YN"	VARCHAR2(1)		NULL,
	"NOT_QUAL_REASON"	VARCHAR2(500)		NULL,
	"PRIVACY_AGREE_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"PRIVACY_AGREE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"HOME_PHONE"	VARCHAR2(100)		NULL,
	"OFFICE_PHONE"	VARCHAR2(100)		NULL,
	"MOB_PHONE"	VARCHAR2(100)		NOT NULL,
	"POSTAL_CODE"	VARCHAR2(5)		NOT NULL,
	"ADDRESS"	VARCHAR2(500)		NOT NULL,
	"DETAIL_ADDRESS"	VARCHAR2(500)		NOT NULL,
	"CAREER_PERIOD"	VARCHAR2(50)		NULL,
	"CAREER_REASON"	VARCHAR2(500)		NULL,
	"MIL_TYPE"	VARCHAR2(20)		NULL,
	"MIL_RANK"	VARCHAR2(20)		NULL,
	"MIL_START_DATE"	DATE		NULL,
	"MIL_END_DATE"	DATE		NULL,
	"VETERAN_YN"	VARCHAR2(1)		NULL,
	"DISABLED_YN"	VARCHAR2(1)		NULL,
	"PHOTO_UPLD_FILE_CD"	VARCHAR2(20)		NOT NULL,
	"UPLD_FILE_ID"	VARCHAR2(20)		NOT NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_EX_EVAL_JDG" (
	"EX_JDG_CD"	VARCHAR2(20)		NOT NULL,
	"USR_ID"	VARCHAR2(20)		NOT NULL,
	"NM"	VARCHAR2(100)		NOT NULL,
	"PW"	VARCHAR2(100)		NOT NULL,
	"ORG"	VARCHAR2(100)		NOT NULL,
	"MOB_PHONE"	VARCHAR2(100)		NOT NULL,
	"EMAIL"	VARCHAR2(100)		NOT NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_FAC_STAFF" (
	"EMP_CD"	VARCHAR2(20)		NOT NULL,
	"NM"	VARCHAR2(100)		NOT NULL,
	"MOB_PHONE"	VARCHAR2(100)		NOT NULL,
	"EMAIL"	VARCHAR2(100)		NOT NULL,
	"ORG"	VARCHAR2(100)		NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_ANN" (
	"ANN_CD"	VARCHAR2(20)		NOT NULL,
	"ANN_TITLE"	VARCHAR2(50)		NOT NULL,
	"ANN_CNTS"	CLOB		NOT NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_UPLD_FILE" (
	"UPLD_FILE_CD"	VARCHAR2(20)		NOT NULL,
	"FILE_SEQ"	NUMBER(10)		NOT NULL,
	"FILE_NM"	VARCHAR2(200)		NULL,
	"SAVE_FILE_NM"	VARCHAR2(400)		NULL,
	"SAVE_PATH"	VARCHAR2(500)		NULL,
	"FILE_SIZ"	VARCHAR2(50)		NULL,
	"FILE_EXTN"	VARCHAR2(50)		NULL,
	"IMG_WIDTH"	VARCHAR2(10)		NULL,
	"IMG_HGT"	VARCHAR2(10)		NULL,
	"UPLD_DTM"	VARCHAR2(14)		NULL,
	"REMARKS"	VARCHAR2(500)		NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)	NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_NTC_STEP" (
	"STEP_CD"	VARCHAR2(20)		NOT NULL,
	"NTC_CD"	VARCHAR2(20)		NOT NULL,
	"STEP"	VARCHAR2 (1)		NOT NULL,
	"STEP_START_DATE"	DATE		NOT NULL,
	"STEP_END_DATE"	DATE		NOT NULL,
	"STEP_ANN_DATE"	DATE		NOT NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_APP_JOB_PLAN" (
	"JOB_PLAN_CD"	VARCHAR2(20)		NOT NULL,
	"APP_CD"	VARCHAR2(20)		NOT NULL,
	"JOB_PLAN_CNTS"	CLOB		NOT NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_NTC_DOC" (
	"NTC_DOC_CD"	VARCHAR2(20)		NOT NULL,
	"DOC_SEQ"	NUMBER(10)		NOT NULL,
	"NTC_INFO_CD"	VARCHAR2(20)		NOT NULL,
	"DOC_CD"	VARCHAR2(20)		NOT NULL,
	"DOC_DESC"	VARCHAR2(300)		NULL,
	"FILE_EXTN"	VARCHAR2(20)		NOT NULL,
	"REQUIRED_YN"	VARCHAR2(1)	DEFAULT 'Y'	NOT NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_SRCH_HST" (
	"SRCH_HST_CD"	VARCHAR2(20)		NOT NULL,
	"USR_ID"	VARCHAR2(20)		NOT NULL,
	"SYS_MENU_CD"	VARCHAR2(20)		NOT NULL,
	"ACS_PGM_URI"	VARCHAR2(200)		NOT NULL,
	"SYS_CD"	VARCHAR2(20)		NOT NULL,
	"EXE_TYPE"	VARCHAR2(20)		NOT NULL,
	"EXE_DATE"	DATE		NOT NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_NTC_FIELD" (
	"FIELD_CD"	VARCHAR2(20)		NOT NULL,
	"NTC_CD"	VARCHAR2(20)		NOT NULL,
	"COLLEGE_CD"	VARCHAR2(20)		NOT NULL,
	"DEPT_CD"	VARCHAR2(20)		NOT NULL,
	"MAJOR_NM"	VARCHAR2(20)		NOT NULL,
	"STAFF_TYPE"	VARCHAR2(20)		NOT NULL,
	"REQUIRED_CNY"	NUMBER(3)		NOT NULL,
	"REQUIREMENTS"	VARCHAR2(1000)		NULL,
	"ASSIGNED_SUBJECT"	VARCHAR2(500)		NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_APP_EDU" (
	"EDU_CD"	VARCHAR2(20)		NOT NULL,
	"APP_CD"	VARCHAR2(20)		NOT NULL,
	"EDU_TYPE"	VARCHAR2(20)		NOT NULL,
	"EDU_START_DATE"	DATE		NOT NULL,
	"EDU_END_DATE"	DATE		NOT NULL,
	"COUNTRY_CD"	VARCHAR2(20)		NOT NULL,
	"SCHOOL_CD"	VARCHAR2(20)		NULL,
	"SCHOOL_NM"	VARCHAR2(100)		NOT NULL,
	"MAJOR"	VARCHAR2(100)		NULL,
	"MAJOR_ DETAIL"	VARCHAR2(100)		NULL,
	"DEGREE_NM"	VARCHAR2(100)		NULL,
	"ACQ_TYPE"	VARCHAR2(20)		NOT NULL,
	"GPA"	NUMBER(3,2)		NULL,
	"MAX_GPA"	VARCHAR2(20)		NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_EVAL_SCH" (
	"SCH_CD"	VARCHAR2(20)		NOT NULL,
	"STEP_CD"	VARCHAR2(20)		NOT NULL,
	"APP_CD"	VARCHAR2(20)		NOT NULL,
	"EVAL_DATE_SCH"	DATE		NOT NULL,
	"EVAL_PLACE_SCH"	VARCHAR2(50)		NOT NULL,
	"EVAL_METHOD_SCH"	VARCHAR2(50)		NOT NULL,
	"DEPT_NAME"	VARCHAR2(20)		NOT NULL,
	"DEPT_PHONE"	VARCHAR2(20)		NOT NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_BRD_POST" (
	"POST_CD"	VARCHAR2(20)		NOT NULL,
	"BRD_CD"	VARCHAR2(20)		NOT NULL,
	"BRD_TYPE"	VARCHAR2(20)		NOT NULL,
	"CATEGORY"	VARCHAR2(20)		NULL,
	"POST_TITLE"	VARCHAR2(200)		NOT NULL,
	"POST_CNTS"	CLOB		NULL,
	"UPR_POST_CD"	VARCHAR2(20)		NULL,
	"RECEIPT_NO"	VARCHAR2(15)		NULL,
	"ANSWER_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"WRITER_NM"	VARCHAR2(100)		NOT NULL,
	"WRITER_PHONE"	VARCHAR2(100)		NULL,
	"PW"	VARCHAR2(100)		NULL,
	"VIEW_CNT"	NUMBER(4)	DEFAULT 0	NOT NULL,
	"IMPORTANT_YN"	VARCHAR2(1)		NULL,
	"SORT_ORDER"	NUMBER(5)		NULL,
	"BRD_POST_STATUS"	VARCHAR2(20)		NULL,
	"UPLD_FILE_ID"	VARCHAR2(20)		NOT NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_BRD" (
	"BRD_CD"	VARCHAR2(20)		NOT NULL,
	"BRD_NM"	VARCHAR2(200)		NOT NULL,
	"BRD_TYPE"	VARCHAR2(20)		NOT NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_EVAL_SHEET_QST" (
	"QST_CD"	VARCHAR2(20)		NOT NULL,
	"SHEET_CD"	VARCHAR2(20)		NOT NULL,
	"QST_TYPE"	VARCHAR2(20)		NOT NULL,
	"QST_NM"	VARCHAR2(200)		NOT NULL,
	"QST_SCORE"	NUMBER(3)		NOT NULL,
	"IND_NM"	VARCHAR2(500)		NOT NULL,
	"IND_SCORE"	NUMBER(3)		NOT NULL,
	"SCORE_CRITERIA"	VARCHAR2(500)		NOT NULL,
	"SORT_ORDER"	NUMBER(3)		NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_APP_THESIS" (
	"THESIS_CD"	VARCHAR2(20)		NOT NULL,
	"APP_CD"	VARCHAR2(20)		NOT NULL,
	"THESIS_DIV"	VARCHAR2(20)		NOT NULL,
	"ORG_LANG_PPR_NM"	VARCHAR(300)		NOT NULL,
	"PBLC_DATE"	DATE		NULL,
	"PBLC_NTN_CD"	VARCHAR2(20)		NULL,
	"SCHOOL_CD"	VARCHAR2(20)		NULL,
	"SCHOOL_NM"	VARCHAR2(100)		NULL,
	"TUTOR_NM"	VARCHAR2(100)		NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_APP_RSCH" (
	"RSCH_CD"	VARCHAR2(20)		NOT NULL,
	"APP_CD"	VARCHAR2(20)		NOT NULL,
	"SCJNL_DVS_CD"	VARCHAR2(20)		NULL,
	"OVRS_PBLC_CD"	VARCHAR2(20)		NULL,
	"KRF_PBLC_CD"	VARCHAR2(20)		NULL,
	"ORG_LANG_PPR_NM"	VARCHAR2(300)		NOT NULL,
	"PBLC_DATE"	DATE		NULL,
	"PBLC_NTN_CD"	VARCHAR2(20)		NULL,
	"SCJNL_NN"	VARCHAR2(300)		NULL,
	"PBLC_PLC_NM"	VARCHAR2(150)		NULL,
	"PPR_LANG_DVS_CD"	VARCHAR2(20)		NULL,
	"TOTAL_ATHR_CNT"	NUMBER(3)		NULL,
	"TPI_DVS_CD"	VARCHAR2(20)		NULL,
	"IMPCT_FCTR"	NUMBER(5,2)		NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_APP_BOOK" (
	"BOOK_CD"	VARCHAR2(20)		NOT NULL,
	"APP_CD"	VARCHAR2(20)		NOT NULL,
	"BOOK_DVS_CD"	VARCHAR2(20)		NULL,
	"BOOK_CHAR_CD"	VARCHAR2(20)		NULL,
	"RVSN_CD"	VARCHAR2(20)		NULL,
	"ORG_LANG_BOOK_NM"	VARCHAR2(300)		NOT NULL,
	"PBLC_DATE"	DATE		NULL,
	"PBLC_PLC_NM"	VARCHAR2(150)		NULL,
	"JNL_DVS_CD"	VARCHAR2(20)		NULL,
	"TOTAL_ATHR_CNT"	NUMBER(3)		NULL,
	"TPI_DVS_CD"	VARCHAR2(20)		NULL,
	"ISBN_NO"	VARCHAR2(50)		NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_APP_SBJT" (
	"SBJT_CD"	VARCHAR2(20)		NOT NULL,
	"APP_CD"	VARCHAR2(20)		NOT NULL,
	"ORG_LANG_SBJT_NM"	VARCHAR2(1000)		NOT NULL,
	"SBJT_START_DATE"	DATE		NULL,
	"SBJT_END_DATE"	DATE		NULL,
	"ROLE_DIV"	VARCHAR2(20)		NULL,
	"APPLY_PER"	NUMBER(5,2)		NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_APP_ITL" (
	"ITL_CD"	VARCHAR2(20)		NOT NULL,
	"APP_CD"	VARCHAR2(20)		NOT NULL,
	"ITL_PPR_RGT_DVS_CD"	VARCHAR2(20)		NULL,
	"ACQS_NTN_DVS_CD"	VARCHAR2(20)		NULL,
	"ACQS_DVS_CD"	VARCHAR2(20)		NULL,
	"ACQS_DTL_DVS_CD"	VARCHAR2(20)		NULL,
	"ITL_PPR_RGT_NM"	VARCHAR2(300)		NOT NULL,
	"APPL_REG_NTN_CD"	VARCHAR2(20)		NULL,
	"APPL_REG_DATE"	DATE		NULL,
	"APPL_REG_NO"	VARCHAR2(50)		NULL,
	"APPL_REGT_NM"	VARCHAR2(150)		NULL,
	"INVT_CNT"	NUMBER(3)		NULL,
	"INVT_NM"	VARCHAR2(100)		NULL,
	"ITL_PPR_RGT_REG_DATE"	DATE		NULL,
	"ITL_PPR_RGT_REG_NO"	VARCHAR2(50)		NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_APP_CFRC" (
	"CFRC_CD"	VARCHAR2(20)		NOT NULL,
	"APP_CD"	VARCHAR2(20)		NOT NULL,
	"CFRC_DVS_CD"	VARCHAR2(20)		NULL,
	"CFRC_NM"	VARCHAR2(300)		NOT NULL,
	"CFRC_HCTR_CD"	VARCHAR2(20)		NULL,
	"ORG_LANG_PPR_NM"	VARCHAR2(1000)		NULL,
	"SCTF_CFRC_ANCM_CLCT_PPR_NM"	VARCHAR2(100)		NULL,
	"HLD_AGC_NM"	VARCHAR2(150)		NULL,
	"ANCM_DATE"	DATE		NULL,
	"ATHR_DVS_CD"	VARCHAR2(20)		NULL,
	"TOTAL_ATHR_CNT"	NUMBER(3)		NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

CREATE TABLE "TB_APP_AMCM" (
	"AMCM_CD"	VARCHAR2(20)		NOT NULL,
	"APP_CD"	VARCHAR2(20)		NOT NULL,
	"ANCM_ACPS_DVS_CD"	VARCHAR2(20)		NULL,
	"ANCM_DATE"	DATE		NULL,
	"ANCM_NTN_CD"	VARCHAR2(20)		NULL,
	"PLAN_MNG_CRP_NM"	VARCHAR2(400)		NULL,
	"ORG_LANG_XHBT_ANCM_NM"	VARCHAR2(400)		NULL,
	"ANUC_PE_CNT"	NUMBER(3)		NULL,
	"DEL_YN"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"CRE_USR_CD"	VARCHAR2(50)		NULL,
	"CRE_PGM"	VARCHAR2(100)		NULL,
	"CRE_IP"	VARCHAR2(20)		NULL,
	"CRE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"UPD_USR_CD"	VARCHAR2(50)		NULL,
	"UPD_PGM"	VARCHAR2(100)		NULL,
	"UPD_IP"	VARCHAR2(20)		NULL,
	"UPD_DATE"	DATE	DEFAULT SYSDATE	NULL
) TABLESPACE TS_RCT_DAT;

-- TB_APP_LANG
CREATE UNIQUE INDEX PK_TB_APP_LANG_IDX ON TB_APP_LANG(LANG_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_APP_LANG ADD CONSTRAINT PK_TB_APP_LANG PRIMARY KEY (LANG_CD) USING INDEX PK_TB_APP_LANG_IDX;

-- TB_SEL_EVAL_JDG
CREATE UNIQUE INDEX PK_TB_SEL_EVAL_JDG_IDX ON TB_SEL_EVAL_JDG(JDG_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_SEL_EVAL_JDG ADD CONSTRAINT PK_TB_SEL_EVAL_JDG PRIMARY KEY (JDG_CD) USING INDEX PK_TB_SEL_EVAL_JDG_IDX;

-- TB_NTC_INFO
CREATE UNIQUE INDEX PK_TB_NTC_INFO_IDX ON TB_NTC_INFO(NTC_INFO_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_NTC_INFO ADD CONSTRAINT PK_TB_NTC_INFO PRIMARY KEY (NTC_INFO_CD) USING INDEX PK_TB_NTC_INFO_IDX;

-- TB_NTC
CREATE UNIQUE INDEX PK_TB_NTC_IDX ON TB_NTC(NTC_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_NTC ADD CONSTRAINT PK_TB_NTC PRIMARY KEY (NTC_CD) USING INDEX PK_TB_NTC_IDX;

-- TB_APP_TR
CREATE UNIQUE INDEX PK_TB_APP_TR_IDX ON TB_APP_TR(TR_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_APP_TR ADD CONSTRAINT PK_TB_APP_TR PRIMARY KEY (TR_CD) USING INDEX PK_TB_APP_TR_IDX;

-- TB_APP_SELF_INTRO
CREATE UNIQUE INDEX PK_TB_APP_SELF_INTRO_IDX ON TB_APP_SELF_INTRO(INTRO_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_APP_SELF_INTRO ADD CONSTRAINT PK_TB_APP_SELF_INTRO PRIMARY KEY (INTRO_CD) USING INDEX PK_TB_APP_SELF_INTRO_IDX;

-- TB_EVAL_SCORE
CREATE UNIQUE INDEX PK_TB_EVAL_SCORE_IDX ON TB_EVAL_SCORE(SCORE_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_EVAL_SCORE ADD CONSTRAINT PK_TB_EVAL_SCORE PRIMARY KEY (SCORE_CD) USING INDEX PK_TB_EVAL_SCORE_IDX;

-- TB_APP_USR
CREATE UNIQUE INDEX PK_TB_APP_USR_IDX ON TB_APP_USR(APP_USR_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_APP_USR ADD CONSTRAINT PK_TB_APP_USR PRIMARY KEY (APP_USR_CD) USING INDEX PK_TB_APP_USR_IDX;

-- TB_CMM
CREATE UNIQUE INDEX PK_TB_CMM_IDX ON TB_CMM(LRG_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_CMM ADD CONSTRAINT PK_TB_CMM PRIMARY KEY (LRG_CD) USING INDEX PK_TB_CMM_IDX;

-- TB_APP
CREATE UNIQUE INDEX PK_TB_APP_IDX ON TB_APP(APP_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_APP ADD CONSTRAINT PK_TB_APP PRIMARY KEY (APP_CD) USING INDEX PK_TB_APP_IDX;

-- TB_EX_EVAL_JDG
CREATE UNIQUE INDEX PK_TB_EX_EVAL_JDG_IDX ON TB_EX_EVAL_JDG(EX_JDG_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_EX_EVAL_JDG ADD CONSTRAINT PK_TB_EX_EVAL_JDG PRIMARY KEY (EX_JDG_CD) USING INDEX PK_TB_EX_EVAL_JDG_IDX;

-- TB_FAC_STAFF
CREATE UNIQUE INDEX PK_TB_FAC_STAFF_IDX ON TB_FAC_STAFF(EMP_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_FAC_STAFF ADD CONSTRAINT PK_TB_FAC_STAFF PRIMARY KEY (EMP_CD) USING INDEX PK_TB_FAC_STAFF_IDX;

-- TB_ANN
CREATE UNIQUE INDEX PK_TB_ANN_IDX ON TB_ANN(ANN_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_ANN ADD CONSTRAINT PK_TB_ANN PRIMARY KEY (ANN_CD) USING INDEX PK_TB_ANN_IDX;

-- TB_UPLD_FILE (복합키)
CREATE UNIQUE INDEX PK_TB_UPLD_FILE_IDX ON TB_UPLD_FILE(UPLD_FILE_CD, FILE_SEQ) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_UPLD_FILE ADD CONSTRAINT PK_TB_UPLD_FILE PRIMARY KEY (UPLD_FILE_CD, FILE_SEQ) USING INDEX PK_TB_UPLD_FILE_IDX;

-- TB_NTC_STEP
CREATE UNIQUE INDEX PK_TB_NTC_STEP_IDX ON TB_NTC_STEP(STEP_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_NTC_STEP ADD CONSTRAINT PK_TB_NTC_STEP PRIMARY KEY (STEP_CD) USING INDEX PK_TB_NTC_STEP_IDX;

-- TB_APP_JOB_PLAN
CREATE UNIQUE INDEX PK_TB_APP_JOB_PLAN_IDX ON TB_APP_JOB_PLAN(JOB_PLAN_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_APP_JOB_PLAN ADD CONSTRAINT PK_TB_APP_JOB_PLAN PRIMARY KEY (JOB_PLAN_CD) USING INDEX PK_TB_APP_JOB_PLAN_IDX;

-- TB_NTC_DOC (복합키)
CREATE UNIQUE INDEX PK_TB_NTC_DOC_IDX ON TB_NTC_DOC(NTC_DOC_CD, DOC_SEQ) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_NTC_DOC ADD CONSTRAINT PK_TB_NTC_DOC PRIMARY KEY (NTC_DOC_CD, DOC_SEQ) USING INDEX PK_TB_NTC_DOC_IDX;

-- TB_SRCH_HST
CREATE UNIQUE INDEX PK_TB_SRCH_HST_IDX ON TB_SRCH_HST(SRCH_HST_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_SRCH_HST ADD CONSTRAINT PK_TB_SRCH_HST PRIMARY KEY (SRCH_HST_CD) USING INDEX PK_TB_SRCH_HST_IDX;

-- TB_NTC_FIELD
CREATE UNIQUE INDEX PK_TB_NTC_FIELD_IDX ON TB_NTC_FIELD(FIELD_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_NTC_FIELD ADD CONSTRAINT PK_TB_NTC_FIELD PRIMARY KEY (FIELD_CD) USING INDEX PK_TB_NTC_FIELD_IDX;

-- TB_APP_EDU
CREATE UNIQUE INDEX PK_TB_APP_EDU_IDX ON TB_APP_EDU(EDU_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_APP_EDU ADD CONSTRAINT PK_TB_APP_EDU PRIMARY KEY (EDU_CD) USING INDEX PK_TB_APP_EDU_IDX;

-- TB_EVAL_SCH
CREATE UNIQUE INDEX PK_TB_EVAL_SCH_IDX ON TB_EVAL_SCH(SCH_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_EVAL_SCH ADD CONSTRAINT PK_TB_EVAL_SCH PRIMARY KEY (SCH_CD) USING INDEX PK_TB_EVAL_SCH_IDX;

-- TB_BRD_POST
CREATE UNIQUE INDEX PK_TB_BRD_POST_IDX ON TB_BRD_POST(POST_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_BRD_POST ADD CONSTRAINT PK_TB_BRD_POST PRIMARY KEY (POST_CD) USING INDEX PK_TB_BRD_POST_IDX;

-- TB_BRD
CREATE UNIQUE INDEX PK_TB_BRD_IDX ON TB_BRD(BRD_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_BRD ADD CONSTRAINT PK_TB_BRD PRIMARY KEY (BRD_CD) USING INDEX PK_TB_BRD_IDX;

-- TB_EVAL_SHEET_QST
CREATE UNIQUE INDEX PK_TB_EVAL_SHEET_QST_IDX ON TB_EVAL_SHEET_QST(QST_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_EVAL_SHEET_QST ADD CONSTRAINT PK_TB_EVAL_SHEET_QST PRIMARY KEY (QST_CD) USING INDEX PK_TB_EVAL_SHEET_QST_IDX;

-- TB_SYS_MENU
CREATE UNIQUE INDEX PK_TB_SYS_MENU_IDX ON TB_SYS_MENU(MENU_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_SYS_MENU ADD CONSTRAINT PK_TB_SYS_MENU PRIMARY KEY (MENU_CD) USING INDEX PK_TB_SYS_MENU_IDX;

-- TB_APP_THESIS
CREATE UNIQUE INDEX PK_TB_APP_THESIS_IDX ON TB_APP_THESIS(THESIS_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_APP_THESIS ADD CONSTRAINT PK_TB_APP_THESIS PRIMARY KEY (THESIS_CD) USING INDEX PK_TB_APP_THESIS_IDX;

-- TB_APP_RSCH
CREATE UNIQUE INDEX PK_TB_APP_RSCH_IDX ON TB_APP_RSCH(RSCH_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_APP_RSCH ADD CONSTRAINT PK_TB_APP_RSCH PRIMARY KEY (RSCH_CD) USING INDEX PK_TB_APP_RSCH_IDX;

-- TB_APP_BOOK
CREATE UNIQUE INDEX PK_TB_APP_BOOK_IDX ON TB_APP_BOOK(BOOK_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_APP_BOOK ADD CONSTRAINT PK_TB_APP_BOOK PRIMARY KEY (BOOK_CD) USING INDEX PK_TB_APP_BOOK_IDX;

-- TB_APP_ITL
CREATE UNIQUE INDEX PK_TB_APP_ITL_IDX ON TB_APP_ITL(ITL_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_APP_ITL ADD CONSTRAINT PK_TB_APP_ITL PRIMARY KEY (ITL_CD) USING INDEX PK_TB_APP_ITL_IDX;

-- TB_APP_AMCM
CREATE UNIQUE INDEX PK_TB_APP_AMCM_IDX ON TB_APP_AMCM(AMCM_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_APP_AMCM ADD CONSTRAINT PK_TB_APP_AMCM PRIMARY KEY (AMCM_CD) USING INDEX PK_TB_APP_AMCM_IDX;

-- TB_APP_CFRC
CREATE UNIQUE INDEX PK_TB_APP_CFRC_IDX ON TB_APP_CFRC(CFRC_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_APP_CFRC ADD CONSTRAINT PK_TB_APP_CFRC PRIMARY KEY (CFRC_CD) USING INDEX PK_TB_APP_CFRC_IDX;

-- TB_APP_SBJT
CREATE UNIQUE INDEX PK_TB_APP_SBJT_IDX ON TB_APP_SBJT(SBJT_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_APP_SBJT ADD CONSTRAINT PK_TB_APP_SBJT PRIMARY KEY (SBJT_CD) USING INDEX PK_TB_APP_SBJT_IDX;

-- TB_APP_AWARD
CREATE UNIQUE INDEX PK_TB_APP_AWARD_IDX ON TB_APP_AWARD(AWARD_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_APP_AWARD ADD CONSTRAINT PK_TB_APP_AWARD PRIMARY KEY (AWARD_CD) USING INDEX PK_TB_APP_AWARD_IDX;

-- TB_APP_CAREER
CREATE UNIQUE INDEX PK_TB_APP_CAREER_IDX ON TB_APP_CAREER(CAREER_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_APP_CAREER ADD CONSTRAINT PK_TB_APP_CAREER PRIMARY KEY (CAREER_CD) USING INDEX PK_TB_APP_CAREER_IDX;

-- TB_APP_REC
CREATE UNIQUE INDEX PK_TB_APP_REC_IDX ON TB_APP_REC(REC_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_APP_REC ADD CONSTRAINT PK_TB_APP_REC PRIMARY KEY (REC_CD) USING INDEX PK_TB_APP_REC_IDX;

-- TB_EVAL_RESULT
CREATE UNIQUE INDEX PK_TB_EVAL_RESULT_IDX ON TB_EVAL_RESULT(RESULT_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_EVAL_RESULT ADD CONSTRAINT PK_TB_EVAL_RESULT PRIMARY KEY (RESULT_CD) USING INDEX PK_TB_EVAL_RESULT_IDX;

-- TB_EVAL_SHEET
CREATE UNIQUE INDEX PK_TB_EVAL_SHEET_IDX ON TB_EVAL_SHEET(SHEET_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_EVAL_SHEET ADD CONSTRAINT PK_TB_EVAL_SHEET PRIMARY KEY (SHEET_CD) USING INDEX PK_TB_EVAL_SHEET_IDX;

-- TB_EVAL_TOTAL_SCORE
CREATE UNIQUE INDEX PK_TB_EVAL_TOTAL_SCORE_IDX ON TB_EVAL_TOTAL_SCORE(TOTAL_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_EVAL_TOTAL_SCORE ADD CONSTRAINT PK_TB_EVAL_TOTAL_SCORE PRIMARY KEY (TOTAL_CD) USING INDEX PK_TB_EVAL_TOTAL_SCORE_IDX;

-- TB_MSG_SND_HST
CREATE UNIQUE INDEX PK_TB_MSG_SND_HST_IDX ON TB_MSG_SND_HST(MSG_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_MSG_SND_HST ADD CONSTRAINT PK_TB_MSG_SND_HST PRIMARY KEY (MSG_CD) USING INDEX PK_TB_MSG_SND_HST_IDX;

-- TB_SYS_ACS_HST
CREATE UNIQUE INDEX PK_TB_SYS_ACS_HST_IDX ON TB_SYS_ACS_HST(SYS_ACS_HST_CD) TABLESPACE TS_RCT_IDX;
ALTER TABLE TB_SYS_ACS_HST ADD CONSTRAINT PK_TB_SYS_ACS_HST PRIMARY KEY (SYS_ACS_HST_CD) USING INDEX PK_TB_SYS_ACS_HST_IDX;


CREATE VIEW VW_USR (
   USR_CD,
   USR_ID,
   USR_TYPE,
   NM,
   PW,
   ORG,
   MOB_PHONE,
   EMAIL
)
SELECT USR_CD AS USR_CD,
       USR_CD AS USR_ID,
       '100'  AS USR_TYPE,
       NM     AS NM,
       '1'    AS PW,
       ORG    AS ORG,
       MOB_PHONE,
       EMAIL
  FROM TB_FAC_STAFF
 UNION ALL
SELECT EX_JDG_CD AS USR_CD,
       USR_ID    AS USR_ID,
       '200'     AS USR_TYPE,
       NM        AS NM,
       PW        AS PW,
       ORG       AS ORG,
       MOB_PHONE,
       EMAIL
  FROM TB_EX_EVAL_JDG
 WHERE DEL_YN = 'N'
 UNION ALL
SELECT APP_USR_CD AS USR_CD,
       USR_ID     AS USR_ID,
       '300'      AS USR_TYPE,
       NM         AS NM,
       PW         AS PW,
       ORG        AS ORG,
       MOB_PHONE,
       EMAIL
  FROM TB_APP_USR
 WHERE DEL_YN = 'N';

CREATE OR REPLACE VIEW VW_ERP_USR AS
SELECT 
   EMP_CD     AS USR_CD,
   NM         AS NM,
   ORG        AS ORG
FROM TB_FAC_STAFF;

CREATE OR REPLACE VIEW VW_DEPT AS
SELECT 
   DEPT_CD,
   UP_CD,
   DEPT_LVL,
   DEPT_NM,
   CAMPUS_DIV,
   USE_YN
FROM TB_DEPT;